version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persiste os dados do DB

  api:
    build: . # Constrói a imagem a partir do Dockerfile na pasta atual
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    # Configurações iniciais de recursos (serão alteradas nos testes)
    # Exemplo para 0.5 vCPU e 128MB RAM
    deploy:
      resources:
        limits:
          cpus: '0.5' # 0.5 vCPU
          memory: 128M # 128 MB de RAM
volumes:
  db_data: